language: python
sudo: false
python:
- '3.6'
- 3.7-dev
install:
- pip install tox
script:
- tox -v -e py
deploy:
  provider: pypi
  user: thomassampson
  password:
    secure: Q2qQPqbDmT/ORr2k7j9N8piLYADvVMIEh3I/9S9En57WAX2Eik2vXelkoHkvxMIGzD5JXpuMZQKwh3fVDx2+SEoyEeXAdHAF2eskFT7hQ2CuOzuet5YsyQDUbwhKlY9I3400IdOx4IGNMwXqYFMQ+CrwV06MsRa0oK46cbjG8Fx9c9HN7CDHaO5qgY/8gEb1iJwsAVeVkCa5p0r0aSE4mfdetqkv06HFGOv1cejPYxTd+hFJ8tMk4MSvHAyf74TLFZtTtqsBfWppfs06ZzjbRzB1AG2BJvMXec60pqu8KxayukUMf2FZ2R+XQtrunj3mih+nRI5bGK0PgveNzR1GY6wro14fvpZGs665enY5IByaBqLJ+/dB2lDS0UIPkomRqhGeIZ+xl9XLFzNwzK41KzXRWC4Dhrg0Jc3jMz7YnKRimt4WrGtZBs5jHCMPSfLLqoOd2+ii7FYyScDvGZZGVmTYNR3/7FzFn82zmgX1UM+H1XdC+wuDONFnY6LGB9sO0U8KipVR4JnrXdGKsdv2OAJTQnUbiEiWYD30LLYFOzoFeI8rpNf6f3t54gDZuAme4BlQGjZMdYEakiNnBWZowRnhrHsayKLFj6TaXj+7LvuxxCXYVjXtazOYmUGTuBhndULfiyOSGITeIFFyeFsFKTPq9t10XIj6sk478I7F8HE=
  tags: true
  distributions: sdist bdist_wheel
